resources:
- ../base/
commonLabels:
  app: todo-app
  env: staging

namespace: staging

images:
  - name: jarrioja/todo-app
    newTag: 48922a7

patches:
  - target:
      kind: PersistentVolume
      name: pv
    patch: |
      - op: replace
        path: /spec/local/path
        value: /mnt/disks/staging-mysql
      - op: replace
        path: /metadata/name
        value: staging-pv