resources:
- ../base/
commonLabels:
  app: todo-app
  env: staging

namespace: staging

images:
  - name: jarrioja/todo-app
    newTag: 19df8b8

patches:
  - target:
      kind: PersistentVolume
      name: pv
    patch: |
      - op: replace
        path: /metadata/name
        value: staging-pv
  - target:
      kind: deployment
      name: mysql
    patch: |
      - op: replace
        path: /spec/volumes/0/persistentVolumeClaim/claimName
        value: staging-pv
  - target:
      kind: Ingress
      name: todo-app-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: dev-todo-app.jesusarrioja.com
      