services:
    mysql-db:
        image: mysql:8.4.0
        restart: always
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - .mysql:/var/lib/mysql
        ports:
            - 3306:3306
    todo-app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_DB: ${MYSQL_DB}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - '3000:3000'
        depends_on:
            - mysql-db
