apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- ingress.yml
- mysql-deployment.yml
- mysql-service.yml
- mysql-pvc.yml
- mysql-pv.yml

commonLabels:
  app: todo-app

