resources:
- ../base/

commonLabels:
  app: todo-app
  env: production

images:
  - name: jarrioja/todo-app
    newTag: 2a9f724

patches:
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: todo-app.jesusarrioja.com