name: CI / CD

on:
    push:
        branches: ['main', 'staging']
permissions:
    contents: write

jobs:
    Build-and-push-image-production:
        name: '[Production] Build and push Docker image'
        runs-on: ubuntu-latest
        environment:
            name: production
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v4

            - name: Log in to Docker Hub
              run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag jarrioja/todo-app:$(git rev-parse --short HEAD) --tag jarrioja/todo-app:latest --build-arg MYSQL_HOST=${{ secrets.MYSQL_HOST }} --build-arg MYSQL_USER=${{ secrets.MYSQL_USER }} --build-arg MYSQL_DB=${{ secrets.MYSQL_DB }} --build-arg MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} --build-arg MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}

            - name: Push the Docker image current commit tag
              run: docker push jarrioja/todo-app:$(git rev-parse --short HEAD)

            - name: Push the Docker image latest tag
              run: docker push jarrioja/todo-app:latest

    update-kuztomize-production:
        name: Update kuztomize on production
        runs-on: ubuntu-latest
        needs: Build-and-push-image-production
        environment:
            name: production

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Get short commit hash
              id: vars
              run: echo "short_commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Update production/kustomization.yaml
              run: |
                  sed -i "s|newTag:.*|newTag: "${{ steps.vars.outputs.short_commit_hash }}"|g" kubernetes/production/kustomization.yaml
                  cat kubernetes/production/kustomization.yaml

            - name: Commit changes.
              run: |
                  git add kubernetes/production/kustomization.yaml
                  git commit -m "Update image tag to ${{ steps.vars.outputs.short_commit_hash }}"
                  git push

    Build-and-push-image-staging:
        name: '[Staging] Build and push Docker image'
        runs-on: ubuntu-latest
        environment:
            name: staging
        if: github.ref == 'refs/heads/staging'
        steps:
            - uses: actions/checkout@v4

            - name: Log in to Docker Hub
              run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag jarrioja/todo-app:$(git rev-parse --short HEAD) --build-arg MYSQL_HOST=${{ secrets.MYSQL_HOST }} --build-arg MYSQL_USER=${{ secrets.MYSQL_USER }} --build-arg MYSQL_DB=${{ secrets.MYSQL_DB }} --build-arg MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} --build-arg MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}

            - name: Push the Docker image current commit tag
              run: docker push jarrioja/todo-app:$(git rev-parse --short HEAD)

    update-kuztomize-staging:
        name: Update kuztomize on staging
        runs-on: ubuntu-latest
        needs: Build-and-push-image-staging
        environment:
            name: staging

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Get short commit hash
              id: vars
              run: echo "short_commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Update staging/kustomization.yaml
              run: |
                  sed -i "s|newTag:.*|newTag: "${{ steps.vars.outputs.short_commit_hash }}"|g" kubernetes/staging/kustomization.yaml
                  cat kubernetes/staging/kustomization.yaml

            - name: Commit changes.
              run: |
                  git add kubernetes/staging/kustomization.yaml
                  git commit -m "Update image tag to ${{ steps.vars.outputs.short_commit_hash }}"
                  git push
